
DROP DATABASE if EXISTS VOUCHER;

CREATE DATABASE VOUCHER;

USE VOUCHER;

CREATE TABLE ALUMNOS (
  NumLegajo INT AUTO_INCREMENT PRIMARY KEY,
  Codigo CHAR(3) NOT NULL UNIQUE,
  DNI VARCHAR(10) NOT NULL UNIQUE,
  Nombre VARCHAR(100) NOT NULL,
  Apellido VARCHAR(100) NOT NULL,
  Curso CHAR(2) NOT NULL,
  Division CHAR(2) NOT NULL,
  Turno varchar(10) NOT NULL
);

CREATE TABLE TIPO_VOUCHER (
  id_tipo_voucher INT AUTO_INCREMENT PRIMARY KEY,
  Nombre_comida VARCHAR(50) NOT NULL,
);

CREATE TABLE ASIGNACION_VOUCHER (
  id_asignacion INT AUTO_INCREMENT PRIMARY KEY,
  id_alumno INT,
  id_tipo_vaucher INT,
  FOREING KEY (id_alumno) REFERENCES ALUMNOS (NumLegajo),
  FOREING KEY (id_tipo_vaucher) REFERENCES TIPO_VOUCHER (id_tipo_voucher)
);  
